name: JPCore FHIR Task

on:
  push:
    branches: 
      - 'feature/swg1-CodeSystem修正'
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - '.github/workflows/**'
jobs:
  turn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2
    - name: STEP2 = prepare gtar files for upload to remote site
      run: | 
        echo "SSH_PORT="$SSH_PORT
        echo "env.SSH_PORT="${{ env.SSH_PORT_JPFHIR }}

        echo "SSH_PORTsSC="$SSH_PORTsSC
        echo "secrets.SSH_PORTsSC="${{ secrets.SSH_PORT_JPFHIR }}
      env:
        SSH_PORT: ${{ env.SSH_PORT_JPFHIR }}
        SSH_PORTsSC: ${{ secrets.SSH_PORT_JPFHIR }}
        

      

