name: JPCore FHIR Task

on:
  push:
    branches: 
      - 'feature/swg1-CodeSystem修正'
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - '.github/workflows/**'
jobs:
  turn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    environment: SSH_PORT_JPFHIR 
    steps:
    - uses: actions/checkout@v2
    - name: STEP1 = ssh key generate  for copying all IG files to public JAMI WG Web site 
      run: | 
        echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}
    - name: STEP2 = prepare gtar files for upload to remote site
      run: | 
        echo "SSH_PORT="$SSH_PORT
        echo "secrets.SSH_PORT="${{ secrets.SSH_PORT_JPFHIR }}
        ssh -i key  -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT_JPFHIR }} r2217734@www41.onamae.ne.jp  'ls -l /home/r2217734/public_html/jpfhir.jp/fhir/core/V1B/fsh-generated'
      env:
        SSH_PORT: ${{ secrets.SSH_PORT_JPFHIR }}
        

      

